version: '3.8'

services:
  app:
    image: serversideup/php:8.5-fpm-nginx
    volumes:
      - .:/var/www/html
    environment:
      PHP_UPLOAD_MAX_FILE_SIZE: ${PHP_UPLOAD_MAX_FILE_SIZE:-250M}
      PHP_OPCACHE_ENABLE: ${PHP_OPCACHE_ENABLE:-1}
      AUTORUN_ENABLED: ${AUTORUN_ENABLED:-true}
      DB_CONNECTION: ${DB_CONNECTION:-mysql}
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-webguard}
      DB_USERNAME: ${DB_USERNAME:-webguard}
      DB_PASSWORD: ${DB_PASSWORD:-webguard}
    depends_on:
      - database
      - redis

  database:
    image: mysql:8.0-debian
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-webguard}
      MYSQL_USER: ${DB_USERNAME:-webguard}
      MYSQL_PASSWORD: ${DB_PASSWORD:-webguard}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

  redis:
    image: redis:7-alpine

  scheduler:
    image: serversideup/php:8.5-fpm-nginx
    command: php /var/www/html/artisan schedule:work --verbose --no-interaction
    volumes:
      - .:/var/www/html
    depends_on:
      - app

  queue-worker:
    image: serversideup/php:8.5-fpm-nginx
    command: php /var/www/html/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600 --verbose --no-interaction
    volumes:
      - .:/var/www/html
    depends_on:
      - app
      - redis

  node:
    image: node:24-alpine
    working_dir: /var/w ww/html
    volumes:
      - .:/var/www/html
    entrypoint: [ "npm" ]
