<script lang="ts">
    import { appRoutes } from "$lib/routes";
    import AdminCrudTable from "$lib/components/AdminCrudTable.svelte";

    interface Props { data: { query: { direction: "asc" | "desc"; page: number; perPage: number; role: string; search: string; sort: string }; users: { data: { items: Array<Record<string, unknown>>; pagination: { current_page: number; last_page: number; total: number } }; options: { packages: Array<{ id: string; monitoring_limit: number }>; roles: string[] } } }; }
    let { data }: Props = $props();
</script>

<svelte:head><title>Users | WebGuard</title></svelte:head>
<main class="mx-auto w-[min(78rem,calc(100%_-_2rem))] py-6 sm:py-12"><AdminCrudTable title="Users" description="Manage user accounts, roles, packages, and verification state." singular="user" endpoint="/api/admin/users" pagePath={appRoutes.adminUsers} items={data.users.data.items} pagination={data.users.data.pagination} query={data.query} tableFilters={[{ name: "role", label: "Role", value: data.query.role, options: data.users.options.roles.map((role) => ({ value: role, label: role })) }]} itemLabel={(item) => String(item.email)} columns={[{ key: "name", label: "Name", sortKey: "name" }, { key: "email", label: "Email", sortKey: "email" }, { key: "role", label: "Role", sortKey: "role" }, { key: "package_limit", label: "Monitoring limit" }, { key: "email_verified_at", label: "Verified", format: (value) => value ? "Verified" : "Unverified" }]} fields={[{ name: "name", label: "Name", required: true }, { name: "email", label: "Email", type: "email", required: true }, { name: "password", label: "Password", type: "password", required: true }, { name: "role", label: "Role", type: "select", required: true, options: data.users.options.roles.map((role) => ({ value: role, label: role })) }, { name: "package_id", label: "Package", type: "select", options: [{ value: "", label: "No package" }, ...data.users.options.packages.map((item) => ({ value: item.id, label: `${item.monitoring_limit} monitorings` }))] }]} extraActions={(item) => item.email_verified_at ? [] : [{ label: "Verify email", endpoint: `/api/admin/users/${item.id}/verify` }]} /></main>
